name: task_manager_fullstack
description: "Full Stack Task Manager"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management & Storage
  get: ^4.7.2
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # UI & Validation
  pinput: ^5.0.1

  # Date & Time
  intl: ^0.19.0

  # Pagination
  infinite_scroll_pagination: ^4.1.0

  # HTTP & Network
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.13

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts (if needed later)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
